services:
  db:
    image: postgres:17
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      REDIS_URL: redis://redis:6379/0
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/portfolio
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/portfolio/node_modules
    depends_on:
      - db
      - chrome
  chrome:
    image: seleniarm/standalone-chromium:121.0
    ports:
      - "4444:4444"
  redis:
    image: redis:7.0
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      TZ: Asia/Tokyo
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - db
    volumes:
      - .:/portfolio
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/portfolio/node_modules  
volumes:
  pgdata:
  bundle_data:
  node_modules:
  redis-data: