:concurrency: 15
:queues:
  - chat
  - notification
  - permit
  - default
  - mailers

:scheduler:
  :schedule:
    delete_room:
      cron: '* * */1 * * * *'
      class: DeleteRoomJob
